### ISSUE TITLE
"Edit this page" link is broken for the topics section

### ISSUE THREAD

**Issue by Smyja** [common-workflow-language/user_guide#257]
The "edit this page" link for everything(all topics) in the topics section is broken.
Location of the [Broken Link](https://github.com/common-workflow-language/user_guide/edit/main/topics/index.md): 
 
http://www.commonwl.org/user_guide/topics/index.html

Correct link should include the `src` folder in the path. There's no guide on how to run this locally, i would have created a PR for it but i can't find where it is in the repo. @kinow 
I guess it's the PR with "New structure" that broke it.

**Comment by kinow** [comment]
Hi @Smyja !

>The "edit this page" link for everything(all topics) in the topics section is broken. (…) Correct link should include the src folder in the path. 

Good catch.

>There's no guide on how to run this locally, i would have created a PR for it but i can't find where it is in the repo. @kinow

Check the `CONTRIBUTING.md` file for instructions on how to build the project. It also includes instructions to visualize locally (search for "visualize locally").

> I guess it's the PR with "New structure" that broke it.

Mea culpa. I believe the fix should involve:

1. clone repository
2. build locally
3. confirm the issue (i.e reproduce the bug) locally
4. edit `src/conf.py`, the configuration file for Sphinx

My guess is that it's one of the settings in the `html_context` dictionary :+1: Then preview locally and confirm it works. Create a pull request. Wait for GH Actions to finish building successfully. Click on the ReadTheDocs link to preview it, and confirm the issue was fixed.

Hope that helps!
-Bruno

**Comment by swzCuroverse** [comment]
@Smyja do you think you can do this fix? That would be great if you could.

**Comment by Smyja** [comment]
> @Smyja do you think you can do this fix? That would be great if you could. 

I have fixed it, I created a pr for it. I'm waiting for it to be merged.

**Comment by mr-c** [comment]
I can confirm that @Smyja PR #259 has fixed the issue. Thanks!

**Comment by Smyja** [comment]
@swzCuroverse is this a good first issue?
